version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: legalcore
      POSTGRES_USER: legalcore
      POSTGRES_DB: legalcore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legalcore"]
      interval: 10s
      retries: 5
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
  legal_core:
    build: .
    command: uvicorn src.api.v1.main:router --factory --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
