app = "symbios-legal-core-empty-snow-5174"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  ENV           = "prod"
  DATABASE_URL  = "sqlite:///data/legal_db.sqlite"

[http_service]
  internal_port        = 8000          # ✅ збігається з uvicorn --port 8000
  force_https          = true
  auto_start_machines  = true
  auto_stop_machines   = true          # ❗️ не рядок "stop", має бути true/false
  min_machines_running = 0             # 0 = cold-start, 1 = тримати постійно
  processes            = ["app"]       # опційно; можна прибрати

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"
