openapi: 3.1.0
info:
  title: Symbios Legal Core API
  version: "1.0"
servers:
  - url: https://symbios-legal-core-empty-snow-5174.fly.dev
paths:
  /api/v1/clients:
    get:
      operationId: listClients
      summary: List all clients
      responses:
        "200": { description: OK }
  /api/v1/companies/{edrpou}:
    get:
      operationId: getCompanyInfo
      summary: Get company info
      parameters:
        - name: edrpou
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
  /api/v1/generate/contract:
    post:
      operationId: generateContract
      summary: Generate contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id: { type: integer }
                template_name: { type: string }
              required: [client_id, template_name]
      responses:
        "200": { description: task id }
  /api/v1/generate/lawsuit:
    post:
      operationId: generateLawsuit
      summary: Generate lawsuit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                case_id: { type: integer }
                template_name: { type: string }
              required: [case_id, template_name]
      responses:
        "200": { description: task id }
  /api/v1/email/sync:
    post:
      operationId: syncInbox
      summary: Sync Gmail inbox
      responses:
        "200": { description: task id }
  /api/v1/email:
    get:
      operationId: listEmails
      summary: List stored emails
      responses:
        "200": { description: emails }
  /api/v1/email/send:
    post:
      operationId: sendEmail
      summary: Send an email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmailSendRequest"
      responses:
        "200": { description: queued }
components:
  schemas:
    EmailSendRequest:
      type: object
      properties:
        to: { type: string }
        subject: { type: string }
        body: { type: string }
      required: [to, subject, body]