name: CI

on:
  push:            # ← реагує на будь-який пуш у main
    branches: [ "main" ]
  pull_request:    # ← і на PR у main
    branches: [ "main" ]

permissions:
  contents: read   # потрібен checkout

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest -q
